; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CE75F77A-6E54-4239-BD58-FCDAF4AC3D54}
AppName=常翴垫╰参
AppVerName=常翴垫╰参 1.27
AppPublisher=Jack Chiang
DefaultDirName={pf}\Mermaid
DefaultGroupName=常翴垫╰参
AllowNoIcons=yes
OutputDir=E:\Program\delphi\Mermaid\output
OutputBaseFilename=memaid-setup-v1.27
Compression=lzma
SolidCompression=yes
SetupIconFile=babelfish32.ico

[Languages]
Name: "english"; MessagesFile: "compiler:ChineseTrad-2-5.1.11.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\Program\delphi\Mermaid\Mermaid.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Program\delphi\Mermaid\PurgeDB\PurgeDB.exe"; DestDir: "{app}"; Flags: ignoreversion
; 戈畐
Source: "E:\Program\delphi\Mermaid\output\dbxconnections.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Program\delphi\Mermaid\output\dbxdrivers.ini"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Program\delphi\Mermaid\output\dbxmys.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Program\delphi\Mermaid\output\libmySQL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Program\delphi\Mermaid\output\config.ini"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist uninsneveruninstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\常翴垫╰参"; Filename: "{app}\Mermaid.exe"; WorkingDir: "{app}"
Name: "{group}\埃戈"; Filename: "{app}\PurgeDB.exe"; WorkingDir: "{app}"
Name: "{group}\{cm:UninstallProgram,常翴垫╰参}"; Filename: "{uninstallexe}"; WorkingDir: "{app}"
Name: "{commondesktop}\常翴垫╰参"; Filename: "{app}\Mermaid.exe"; WorkingDir: "{app}"; Tasks: desktopicon
Name: "{commondesktop}\埃戈"; Filename: "{app}\PurgeDB.exe"; WorkingDir: "{app}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\常翴垫╰参"; Filename: "{app}\Mermaid.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\Mermaid.exe"; Description: "{cm:LaunchProgram,常翴垫╰参}"; Flags: nowait postinstall skipifsilent





